build from remote repo (#15)
* chore: avoid "Sources disagree on hashes for supposedly identical version"

* feat: build image from remote(except vyos-1x)

* fix: deb find

* revert

* revert

diff --git a/.github/workflows/auto-build.yml b/.github/workflows/auto-build.yml
--- a/.github/workflows/auto-build.yml
+++ b/.github/workflows/auto-build.yml
@@ -93,50 +93,47 @@ jobs:
           echo "TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
           echo "PREVIOUS_SUCCESS_BUILD_TIMESTAMP=$(cat version.json | jq -r '.[0].timestamp')" >> $GITHUB_OUTPUT
 
-      - name: Build global deps
-        run: |
-          source <(sed -n '/enable programmable completion/,$p' /etc/skel/.bashrc)
-          set -ex
-          eval $(opam env --root=/opt/opam --set-root)
-          mkdir global_deps
-          cd global_deps
-          global_deps=(
-            libvyosconfig
-            vyatta-bash
-            vyatta-biosdevname
-            vyatta-cfg
-            # https://github.com/vyos/vyos-1x/commit/d6a82c134bed0b0921595928b7ec600b2935327b
-            # vyatta-wanloadbalance
-            vyos-utils
-            # Architecture:all, can install directly
-            # vyos-user-utils
-            vyos-http-api-tools
-            # Architecture:all, can install directly
-            # vyos-cloud-init
-            ipaddrcheck
-            udp-broadcast-relay
-            hvinfo
-            # Architecture:all, can install directly
-            # live-boot
-          )
-          for global_dep in ${global_deps[@]}; do
-            git clone https://github.com/vyos/$global_dep
-            cd $global_dep
-
-            echo "y" | mk-build-deps --install --remove
-
-            # should update libvyosconfig due to hardcode on vyos-1x
-            # https://github.com/vyos/vyos-1x/blob/e90a2781f9eae555097e078b9b11dd0dca6c0acd/python/vyos/configtree.py#L22
-            # that will failed on reftree.cache
-            # 2025.03.05: fixed on https://github.com/vyos/vyos-1x/commit/731195c7adb21208767199f5487dfdf29ce09380
-            # if [ "${global_dep}" = "libvyosconfig" ]; then
-            #   ./build.sh
-            #   cp _build/libvyosconfig.so /usr/lib/libvyosconfig.so.0
-            # fi
-
-            dpkg-buildpackage -b -us -uc -tc
-            cd ..
-          done
+      # - name: Build global deps
+      #   run: |
+      #     source <(sed -n '/enable programmable completion/,$p' /etc/skel/.bashrc)
+      #     set -ex
+      #     eval $(opam env --root=/opt/opam --set-root)
+      #     mkdir global_deps
+      #     cd global_deps
+      #     global_deps=(
+      #       libvyosconfig
+      #       vyatta-bash
+      #       vyatta-biosdevname
+      #       vyatta-cfg
+      #       # https://github.com/vyos/vyos-1x/commit/d6a82c134bed0b0921595928b7ec600b2935327b
+      #       # vyatta-wanloadbalance
+      #       vyos-utils
+      #       # Architecture:all, can install directly
+      #       # vyos-user-utils
+      #       vyos-http-api-tools
+      #       # Architecture:all, can install directly
+      #       # vyos-cloud-init
+      #       ipaddrcheck
+      #       udp-broadcast-relay
+      #       hvinfo
+      #       # Architecture:all, can install directly
+      #       # live-boot
+      #     )
+      #     for global_dep in ${global_deps[@]}; do
+      #       git clone https://github.com/vyos/$global_dep
+      #       cd $global_dep
+      #       echo "y" | mk-build-deps --install --remove
+      #       # should update libvyosconfig due to hardcode on vyos-1x
+      #       # https://github.com/vyos/vyos-1x/blob/e90a2781f9eae555097e078b9b11dd0dca6c0acd/python/vyos/configtree.py#L22
+      #       # that will failed on reftree.cache
+      #       # 2025.03.05: fixed on https://github.com/vyos/vyos-1x/commit/731195c7adb21208767199f5487dfdf29ce09380
+      #       # if [ "${global_dep}" = "libvyosconfig" ]; then
+      #       #   ./build.sh
+      #       #   cp _build/libvyosconfig.so /usr/lib/libvyosconfig.so.0
+      #       # fi
+      #       dpkg-buildpackage -b -us -uc -tc
+      #       cd ..
+      #     done
 
       - name: Checkout vyos-build repo
         uses: actions/checkout@v5
@@ -207,7 +204,8 @@ jobs:
           cd vyos-build/scripts/package-build
           source <(sed -n '/enable programmable completion/,$p' /etc/skel/.bashrc)
           set -ex
-          packages=$(ls .)
+          # packages=$(ls .)
+          packages="vyos-1x"
           ignore_packages=(amazon-cloudwatch-agent amazon-ssm-agent xen-guest-agent)
           for package in $packages; do
             [ ! -d $package ] && continue
@@ -272,19 +270,18 @@ jobs:
             fi
             cp $deb_file packages
           done
-          global_deb_files=$(find ../global_deps -name "*.deb" -type f | \
-            grep -v -- -dbg | \
-            grep -v -- -dev | \
-            grep -v -- -doc
-          )
-          for deb_file in $global_deb_files; do
-            cp $deb_file packages
-          done
-          # vpp addition files
-          find scripts/package-build/vpp -name "libvppinfra-dev*.deb" -type f -exec cp {} packages ';'
-          find scripts/package-build/vpp -name "vpp-dev*.deb" -type f -exec cp {} packages ';'
-
-          rm -rf packages/linux-headers-*
+          # global_deb_files=$(find ../global_deps -name "*.deb" -type f | \
+          #   grep -v -- -dbg | \
+          #   grep -v -- -dev | \
+          #   grep -v -- -doc
+          # )
+          # for deb_file in $global_deb_files; do
+          #   cp $deb_file packages
+          # done
+          # # vpp addition files
+          # find scripts/package-build/vpp -name "libvppinfra-dev*.deb" -type f -exec cp {} packages ';'
+          # find scripts/package-build/vpp -name "vpp-dev*.deb" -type f -exec cp {} packages ';'
+          # rm -rf packages/linux-headers-*
           ls -alh packages
 
       - name: Build generic ISO image
@@ -370,7 +367,8 @@ jobs:
     runs-on: ubuntu-24.04
     permissions:
       contents: write
-    if: github.ref_name == "${{ github.event.repository.default_branch }}"
+    # if: github.ref_name == "${{ github.event.repository.default_branch }}"
+    if: github.ref_name == 'master'
     steps:
       - uses: actions/checkout@v5
       - name: Clone vyos-build repo
